/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ana' at '5/27/16 11:33 AM' with Gradle 2.13
 *
 * @author ana, @date 5/27/16 11:33 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
